language: node_js
node_js:
  - "6"
  - "8"
  - "10"
jobs:
  include:
    - script: echo "Running tests against $(node -v) ..." && npm t
    - stage: deploy
      script: npm run semantic-release
stages:
  - test
  - name: deploy
    if: branch = master
